-- DEPRECATED: esquema anterior sin prefijo gst_. Usar GST_unified_schema.sql
-- PostgreSQL DDL Script for Gestion360i Supabase Tables
-- Run this script in the Supabase SQL Editor of your project.

-- TABLA: personal
CREATE TABLE IF NOT EXISTS public.personal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre text NOT NULL,
    razon_social text,
    cuit text,
    saldo numeric(12,2) DEFAULT 0.00 NOT NULL,
    telefono text,
    condicion_iva text DEFAULT 'Consumidor Final'::text NOT NULL,
    direccion_predeterminada text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: cliente_direcciones
CREATE TABLE IF NOT EXISTS public.cliente_direcciones (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    cliente_id uuid REFERENCES public.clientes(id) ON DELETE CASCADE NOT NULL,
    direccion text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: cliente_movimientos
CREATE TABLE IF NOT EXISTS public.cliente_movimientos (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    cliente_id uuid REFERENCES public.clientes(id) ON DELETE CASCADE NOT NULL,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    concepto text NOT NULL,
    debe numeric(12,2) DEFAULT 0.00 NOT NULL,
    haber numeric(12,2) DEFAULT 0.00 NOT NULL
);

-- TABLA: pedidos
CREATE TABLE IF NOT EXISTS public.pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id uuid REFERENCES public.clientes(id) ON DELETE SET NULL,
    total numeric(12,2) DEFAULT 0.00 NOT NULL,
    con_envio boolean DEFAULT false NOT NULL,
    direccion_envio text,
    estado text DEFAULT 'Pendiente'::text NOT NULL,
    repartidor text,
    medio_pago text,
    motivo_cancelacion text,
    cae text,
    cae_vencimiento date,
    factura_nro text,
    factura_fecha date,
    factura_tipo text,
    factura_error text,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: pedido_items
CREATE TABLE IF NOT EXISTS public.pedido_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
    producto text NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    valor numeric(12,2) NOT NULL,
    observacion text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: compras
CREATE TABLE IF NOT EXISTS public.compras (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    proveedor text NOT NULL,
    alias text,
    cuit text,
    tipo text,
    detalle text,
    pago text,
    factura text,
    monto_neto numeric(12,2) DEFAULT 0.00,
    monto_neto_10_5 numeric(12,2) DEFAULT 0.00,
    monto_neto_27 numeric(12,2) DEFAULT 0.00,
    iva_10_5 numeric(12,2) DEFAULT 0.00,
    iva_21 numeric(12,2) DEFAULT 0.00,
    iva_27 numeric(12,2) DEFAULT 0.00,
    monto_exento numeric(12,2) DEFAULT 0.00,
    monto_no_gravado numeric(12,2) DEFAULT 0.00,
    percep_iva numeric(12,2) DEFAULT 0.00,
    percep_iibb numeric(12,2) DEFAULT 0.00,
    iibb_jurisdiccion text,
    percep_ganancias numeric(12,2) DEFAULT 0.00,
    impuestos_internos numeric(12,2) DEFAULT 0.00,
    tasas_municipales numeric(12,2) DEFAULT 0.00,
    total numeric(12,2) NOT NULL,
    caja_cierre text,
    conceptos_desglose jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: proveedores
CREATE TABLE IF NOT EXISTS public.proveedores (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre text NOT NULL UNIQUE,
    cuit text,
    alias text,
    tipo text DEFAULT 'Mercadería'::text,
    detalle text DEFAULT ''::text,
    pago text DEFAULT 'Caja'::text,
    factura text DEFAULT 'Sin factura'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- TABLA: empleado_movimientos
CREATE TABLE IF NOT EXISTS public.empleado_movimientos (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    empleado text NOT NULL,
    concepto text NOT NULL,
    monto numeric(12,2) NOT NULL,
    caja_cierre text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: cierres_caja
CREATE TABLE IF NOT EXISTS public.cierres_caja (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    turno text NOT NULL,
    efectivo numeric(12,2) DEFAULT 0.00 NOT NULL,
    transferencia numeric(12,2) DEFAULT 0.00 NOT NULL,
    tarjeta numeric(12,2) DEFAULT 0.00 NOT NULL,
    qr_pago numeric(12,2) DEFAULT 0.00 NOT NULL,
    link_pago numeric(12,2) DEFAULT 0.00 NOT NULL,
    cta_cte numeric(12,2) DEFAULT 0.00 NOT NULL,
    adelantos_efectivo numeric(12,2) DEFAULT 0.00 NOT NULL,
    adelantos_merc numeric(12,2) DEFAULT 0.00 NOT NULL,
    compras numeric(12,2) DEFAULT 0.00 NOT NULL,
    total numeric(12,2) DEFAULT 0.00 NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: rendiciones
CREATE TABLE IF NOT EXISTS public.rendiciones (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    concepto text NOT NULL,
    debe numeric(12,2) DEFAULT 0.00 NOT NULL,
    haber numeric(12,2) DEFAULT 0.00 NOT NULL,
    categoria text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLA: tareas
CREATE TABLE IF NOT EXISTS public.tareas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caracter text,
    tarea text NOT NULL,
    usuario text DEFAULT 'Empleado'::text NOT NULL,
    estado text DEFAULT 'Pendiente'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
